=== CoCoViLa/CoCoViLa/src/main/resources/package.dtd
<?xml version='1.0' encoding='us-ascii'?>
<!--
  #%L
  CoCoViLa
  %%
  Copyright (C) 2003 - 2017 Institute of Cybernetics at Tallinn University of Technology
  %%
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at
  
       http://www.apache.org/licenses/LICENSE-2.0
  
  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
  #L%
  -->

<!-- The root node of a package -->
<!ELEMENT package	(name, description, daemon?, class*)>
<!-- A single alphanumeric word - no separators allowed -->
<!ELEMENT name	(#PCDATA)>
<!-- specifies the location of a metainterface, default is "<name>.java" -->
<!ELEMENT file	(#PCDATA)>
<!-- fully qualified name of a Java class this specification extends -->
<!ELEMENT extends	(#PCDATA)>
<!-- Free text - may contain many sentences-->
<!ELEMENT description	(#PCDATA)>
<!-- A daemon is a program that controls execution and visualisation of the component -->
<!ELEMENT daemon	(#PCDATA)>
<!-- A .png or .gif picture to be used in the toolbar -->
<!ELEMENT icon	(#PCDATA)>
<!-- A rich component - root node of a class -->
<!ELEMENT class	(name, file?, extends?, description, icon, daemon?, graphics, ports?, fields?)>
<!-- 
	type=class is the usual case, 
	type=relation defines a connection-line style visual appearance. 
	type=scheme defines a scheme as a component and <scheme name>.syn file should exist in the package's folder
	See package state for an example usage 
-->
<!ATTLIST class
	type (relation|class|scheme)	"class"
	static (true|false)	"false"
>
<!-- Field is an attribute of the rich component 
shown in the list of attributes in the Schema Editor.
If a field is 'hidden' it means that it will not be shown in the Object Properties window -->	
<!ELEMENT fields	(field*)>
<!ELEMENT field	(known?,default?)>
<!ATTLIST field 
	name	CDATA   #REQUIRED
	nature	(normal|input|goal)	"normal"
	type	CDATA	#IMPLIED
	value	CDATA	#IMPLIED
	description	CDATA	#IMPLIED
	hidden 	(true|false)	#IMPLIED
>
<!-- Graphics to display some info about the field together with the visual 
appearance of the rich component e.g 'text string="*self"' (or *selfWithName) displays its value -->
<!ELEMENT known	(graphics)>
<!ELEMENT default (graphics)>
<!-- A visual appearance of something composed of vector graphics' shapes and/or raster images -->
<!ELEMENT graphics ( bounds?, ( line | rect | oval | arc | polygon | image | text )*, painter? )>
<!ATTLIST graphics 
	showFields (true|false) "false"
>
<!-- painter of this class graphics -->
<!ELEMENT painter (#PCDATA)>
<!-- An area of the visual appearance that is active i.e. reacts on mouse clicks -->
<!ELEMENT bounds	EMPTY>
<!ATTLIST bounds
	x	CDATA	#REQUIRED
	y	CDATA	#REQUIRED
	width	CDATA	#REQUIRED
	height	CDATA	#REQUIRED       
>
<!-- Vector graphics' shapes for the visual appearance -->
<!-- The attributes (coordinates) x, y are relative to the location of the object 
(properties x, y in the syn file) -->
<!ELEMENT line	EMPTY>
<!ATTLIST line 
	x1	CDATA	#REQUIRED
	y1	CDATA	#REQUIRED
	x2	CDATA	#REQUIRED
	y2	CDATA	#REQUIRED
	colour	CDATA	#IMPLIED
	fixed	(true|false)	#IMPLIED
	stroke	CDATA	#IMPLIED
	transparency	CDATA	#IMPLIED
	linetype	CDATA	#IMPLIED
>
<!-- rectangle -->
<!ELEMENT rect	EMPTY>
<!ATTLIST rect
	x	CDATA	#REQUIRED
	y	CDATA	#REQUIRED
	width	CDATA	#REQUIRED
	height	CDATA	#REQUIRED       
	colour	CDATA   #IMPLIED
	linetype	CDATA	#IMPLIED
	filled	(true|false)	#IMPLIED
	transparency	CDATA	#IMPLIED
	fixed	(true|false)	#IMPLIED
	stroke	CDATA	#IMPLIED
>
<!-- oval -->
<!ELEMENT oval	EMPTY>
<!ATTLIST oval
	x	CDATA	#REQUIRED
	y	CDATA	#REQUIRED
	width	CDATA	#REQUIRED
	height	CDATA	#REQUIRED       
	colour	CDATA   #IMPLIED
	linetype	CDATA	#IMPLIED
	filled	(true|false)	#IMPLIED
	transparency	CDATA	#IMPLIED
	fixed	(true|false)	#IMPLIED
	stroke	CDATA	#IMPLIED
>
<!-- arc -->
<!ELEMENT arc	EMPTY>
<!ATTLIST arc
	x	CDATA	#REQUIRED
	y	CDATA	#REQUIRED
	width	CDATA	#REQUIRED
	height	CDATA	#REQUIRED       
	startAngle	CDATA	#REQUIRED
	arcAngle	CDATA	#REQUIRED
	colour	CDATA	#IMPLIED
	filled	(true|false)	#IMPLIED
	fixed	(true|false)	#IMPLIED
	stroke	CDATA	#IMPLIED
	transparency	CDATA	#IMPLIED
	linetype	CDATA	#IMPLIED
>
<!-- polygon -->
<!ELEMENT polygon	(point+)>
<!ATTLIST polygon
	colour	CDATA	#IMPLIED
	filled	(true|false)	#IMPLIED
	fixed	(true|false)	#IMPLIED
	stroke	CDATA	#IMPLIED
	transparency	CDATA	#IMPLIED
	linetype	CDATA	#IMPLIED
>
<!-- A helper object for polygon -->
<!ELEMENT point	EMPTY>
<!ATTLIST point
	x	CDATA	#REQUIRED
	y	CDATA	#REQUIRED
>
<!-- text -->
<!ELEMENT text	EMPTY>
<!ATTLIST text 
	string	CDATA	#REQUIRED
	colour	CDATA	#IMPLIED
	x	CDATA	#REQUIRED
	y	CDATA	#REQUIRED
	fontname	CDATA	#REQUIRED
	fontstyle	CDATA	#REQUIRED
	fontsize	CDATA	#REQUIRED
	fixed	CDATA	#IMPLIED
	transparency	CDATA	#IMPLIED
>
<!-- A raster image for the visual appearance.
image path should be relative to the package xml -->
<!ELEMENT image	EMPTY>
<!ATTLIST image
	x	CDATA	#REQUIRED
	y	CDATA	#REQUIRED
	width	CDATA	#REQUIRED
	height	CDATA	#REQUIRED       
	path	CDATA	#REQUIRED
	fixed	CDATA	#IMPLIED
>
<!-- Port is a connection point added to the visual appearance of a rich component. 
Port is bound to a metaclasses component via the attribute "name".
Ports are used to connect rich components to each-other 
portConnection=area - used for rendering relation classes
-->
<!ELEMENT ports	(port*)>
<!ELEMENT port	(open?, closed?)>
<!ATTLIST port
	id	CDATA	#IMPLIED
	name	CDATA	#REQUIRED
	type	CDATA	#REQUIRED
	x	CDATA	#REQUIRED
	y	CDATA	#REQUIRED
	portConnection	CDATA #IMPLIED
	strict	CDATA	#IMPLIED
	multi	CDATA	#IMPLIED
>
<!-- Port graphics for open/closed status. For usage example see petrinet.Transition -->
<!ELEMENT open	 (graphics)>
<!ELEMENT closed (graphics)>

<!-- Deprecated?
<!ELEMENT portname	(#PCDATA)>
<!ELEMENT xpos	(#PCDATA)>
<!ELEMENT ypos	(#PCDATA)>
<!ELEMENT datatype	(#PCDATA)>
<!ELEMENT portConnection	EMPTY>
<!ELEMENT strict	EMPTY>
<!ELEMENT multi	EMPTY>
<!ELEMENT type	(#PCDATA)> -->

=== CoCoViLa/CoCoViLa/package/portGraphics.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE package SYSTEM "package.dtd">
<package>
    <name>portGraphics</name>
    <description>Port Graphics</description>
    <class static="false" type="class">
        <name>marineSquare</name>
        <description>port graphics</description>
        <icon>default.gif</icon>
        <graphics>
            <bounds height="0" width="0" x="0" y="0"/>
            <rect colour="-16737895" filled="true" fixed="false"
                height="11" linetype="0.0" stroke="1.0"
                transparency="255" width="12" x="288" y="35"/>
        </graphics>
    </class>
    <class static="false" type="class">
        <name>redDot</name>
        <description>port graphics</description>
        <icon>default.gif</icon>
        <graphics>
            <bounds height="0" width="0" x="0" y="0"/>
            <oval colour="-65485" filled="true" fixed="false" height="9"
                linetype="0.0" stroke="1.0" transparency="255"
                width="10" x="320" y="37"/>
        </graphics>
    </class>
</package>

=== CoCoViLa/CoCoViLa/package/packTT.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE package SYSTEM "package.dtd">
<package>
    <name>packTT</name>
    <description>test</description>
    <class static="false" type="class">
        <name>ClassTT</name>
        <description/>
        <icon/>
        <graphics>
            <bounds height="0" width="0" x="0" y="0"/>
            <rect colour="-16777216" filled="true" fixed="false"
                height="73" linetype="0.0" stroke="1.0"
                transparency="255" width="115" x="82" y="14"/>
            <rect colour="-16777216" filled="true" fixed="false"
                height="73" linetype="0.0" stroke="1.0"
                transparency="255" width="115" x="82" y="14"/>
        </graphics>
    </class>
    <class static="false" type="class">
        <name>blue</name>
        <description>BLUE</description>
        <icon>default.gif</icon>
        <graphics>
            <bounds height="0" width="0" x="0" y="0"/>
            <rect colour="-13421569" filled="true" fixed="true"
                height="58" linetype="0.0" stroke="1.0"
                transparency="255" width="91" x="14" y="5"/>
        </graphics>
    </class>
    <class static="false" type="class">
        <name>portTT</name>
        <description>lalala</description>
        <icon>default.gif</icon>
        <graphics>
            <bounds height="0" width="0" x="0" y="0"/>
            <rect colour="-16777216" filled="false" fixed="false"
                height="74" linetype="0.0" stroke="1.0"
                transparency="255" width="135" x="84" y="22"/>
        </graphics>
        <ports>
            <port multi="false" name="ppt" portConnection=""
                strict="true" type="double" x="10" y="22"/>
        </ports>
    </class>
    <class static="false" type="class">
        <name>shape</name>
        <description>test</description>
        <icon>default.gif</icon>
        <graphics>
            <bounds height="0" width="0" x="0" y="0"/>
            <arc arcAngle="249" colour="-16777216" filled="true"
                fixed="false" height="128" linetype="0.0"
                startAngle="226" stroke="1.0" transparency="255"
                width="124" x="40" y="21"/>
        </graphics>
    </class>
    <class static="false" type="class">
        <name>ball</name>
        <description>ball</description>
        <icon>default.gif</icon>
        <graphics>
            <bounds height="0" width="0" x="0" y="0"/>
            <oval colour="-16777216" filled="true" fixed="false"
                height="131" linetype="0.0" stroke="1.0"
                transparency="255" width="140" x="103" y="28"/>
        </graphics>
        <fields>
            <field name="1" type="long" value="1"/>
        </fields>
    </class>
    <class static="false" type="class">
        <name>1</name>
        <description>1</description>
        <icon>default.gif</icon>
        <graphics>
            <bounds height="0" width="0" x="0" y="0"/>
            <rect colour="-16777216" filled="false" fixed="false"
                height="89" linetype="0.0" stroke="1.0"
                transparency="255" width="149" x="75" y="45"/>
        </graphics>
    </class>
    <class static="false" type="class">
        <name>2</name>
        <description>2</description>
        <icon>default.gif</icon>
        <graphics>
            <bounds height="0" width="0" x="0" y="0"/>
            <rect colour="-16777216" filled="false" fixed="false"
                height="74" linetype="0.0" stroke="1.0"
                transparency="255" width="121" x="134" y="60"/>
            <rect colour="-16777216" filled="false" fixed="false"
                height="114" linetype="0.0" stroke="1.0"
                transparency="255" width="133" x="346" y="274"/>
            <rect colour="-16777216" filled="false" fixed="false"
                height="34" linetype="0.0" stroke="1.0"
                transparency="255" width="53" x="314" y="166"/>
        </graphics>
    </class>
    <class static="false" type="class">
        <name>3</name>
        <description>3</description>
        <icon>default.gif</icon>
        <graphics>
            <bounds height="0" width="0" x="0" y="0"/>
            <rect colour="-16777216" filled="false" fixed="false"
                height="72" linetype="0.0" stroke="1.0"
                transparency="255" width="116" x="123" y="31"/>
        </graphics>
    </class>
    <class static="false" type="class">
        <name>4</name>
        <description>4</description>
        <icon>default.gif</icon>
        <graphics>
            <bounds height="0" width="0" x="0" y="0"/>
            <rect colour="-16777216" filled="false" fixed="false"
                height="102" linetype="0.0" stroke="1.0"
                transparency="255" width="135" x="90" y="47"/>
        </graphics>
    </class>
    <class static="false" type="class">
        <name>5</name>
        <description>5</description>
        <icon>default.gif</icon>
        <graphics>
            <bounds height="0" width="0" x="0" y="0"/>
            <rect colour="-16777216" filled="true" fixed="false"
                height="60" linetype="0.0" stroke="1.0"
                transparency="255" width="111" x="189" y="60"/>
        </graphics>
    </class>
    <class static="false" type="class">
        <name>6</name>
        <description>6</description>
        <icon>default.gif</icon>
        <graphics>
            <bounds height="0" width="0" x="0" y="0"/>
            <rect colour="-16777216" filled="true" fixed="false"
                height="56" linetype="0.0" stroke="1.0"
                transparency="255" width="80" x="176" y="64"/>
        </graphics>
    </class>
    <class static="false" type="class">
        <name>123</name>
        <description>123</description>
        <icon>default.gif</icon>
        <graphics>
            <bounds height="0" width="0" x="0" y="0"/>
            <arc arcAngle="286" colour="-16777216" filled="true"
                fixed="false" height="85" linetype="0.0" startAngle="30"
                stroke="1.0" transparency="255" width="140" x="187" y="56"/>
        </graphics>
    </class>
</package>
